(function(){
'use strict';
var isYearly=false;
function updatePrices(){var y=isYearly;document.querySelectorAll('.precio-number[data-monthly]').forEach(function(n){var m=parseInt(n.dataset.monthly,10);var yr=parseInt(n.dataset.yearly,10);ani(n,parseInt(n.textContent)||0,y?yr:m)});document.querySelectorAll('.period-text').forEach(function(p){p.textContent=y?'/mes · facturado anualmente':'/mes'})}
function ani(el,from,to){if(from===to)return;var d=400,s=null;function step(ts){if(!s)s=ts;var t=Math.min((ts-s)/d,1);var ease=1-Math.pow(1-t,3);el.textContent=Math.floor(from+(to-from)*ease);if(t<1)requestAnimationFrame(step)}requestAnimationFrame(step)}
var lbf=document.getElementById('loaderBarFill');var lt=document.getElementById('loaderText');var ld=document.getElementById('loader');var progress=0;var li=setInterval(function(){progress+=Math.random()*15+5;if(progress>=100){progress=100;clearInterval(li);if(lbf)lbf.style.width='100%';if(lt)lt.textContent='Listo.';setTimeout(function(){if(ld)ld.classList.add('hidden')},300)}else{if(lbf)lbf.style.width=progress+'%';if(lt)lt.textContent=progress<60?'Cargando...':'Preparando...'}},100);
setTimeout(function(){clearInterval(li);if(ld)ld.classList.add('hidden')},5000);
function showToast(msg,color){var t=document.createElement('div');t.style.cssText='position:fixed;top:80px;left:50%;transform:translateX(-50%);padding:10px 24px;border-radius:999px;font-weight:600;font-size:13px;z-index:99999;opacity:0;transition:opacity .4s;background:'+(color||'#3B82F6')+';color:#fff';t.textContent=msg;document.body.appendChild(t);requestAnimationFrame(function(){t.style.opacity='1'});setTimeout(function(){t.style.opacity='0';setTimeout(function(){t.remove()},400)},5000)}
var nav=document.getElementById('nav');var nt=document.getElementById('navToggle');var nl=document.getElementById('navLinks');
window.addEventListener('scroll',function(){var y=window.scrollY;if(nav)nav.classList.toggle('scrolled',y>50)},{passive:true});
if(nt&&nl){nt.addEventListener('click',function(){var o=nl.classList.toggle('open');nt.classList.toggle('active');nt.setAttribute('aria-expanded',o);document.body.style.overflow=o?'hidden':''});nl.querySelectorAll('a').forEach(function(l){l.addEventListener('click',function(){nl.classList.remove('open');nt.classList.remove('active');nt.setAttribute('aria-expanded','false');document.body.style.overflow=''})})}
var canvas=document.getElementById('particleCanvas');if(canvas){var ctx=canvas.getContext('2d'),particles=[],pCount=Math.min(25,Math.floor(window.innerWidth/35));var mouse={x:-1000,y:-1000};function rc(){canvas.width=window.innerWidth;canvas.height=window.innerHeight}rc();var resizeTimer=null;window.addEventListener('resize',function(){clearTimeout(resizeTimer);resizeTimer=setTimeout(rc,150)});document.addEventListener('mousemove',function(e){mouse.x=e.clientX;mouse.y=e.clientY});for(var i=0;i<pCount;i++)particles.push({x:Math.random()*canvas.width,y:Math.random()*canvas.height,vx:(Math.random()-.5)*.15,vy:(Math.random()-.5)*.15,r:Math.random()+.2,c:['#3B82F6','#22D3EE','#34D399','#8B5CF6'][i%4]});(function dp(){ctx.clearRect(0,0,canvas.width,canvas.height);for(var i=0;i<particles.length;i++){var p=particles[i];p.x+=p.vx;p.y+=p.vy;var dx=p.x-mouse.x,dy=p.y-mouse.y,d=Math.sqrt(dx*dx+dy*dy);if(d<60&&d>0){var f=(60-d)/60;p.x+=(dx/d)*f;p.y+=(dy/d)*f}if(p.x<0||p.x>canvas.width)p.vx*=-1;if(p.y<0||p.y>canvas.height)p.vy*=-1;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,6.28);ctx.fillStyle=p.c;ctx.globalAlpha=.15;ctx.fill()}ctx.globalAlpha=1;requestAnimationFrame(dp)})()}
document.querySelectorAll('[data-reveal]').forEach(function(el){el.classList.add('reveal-hidden')});if('IntersectionObserver' in window){var revealObserver=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.remove('reveal-hidden');entry.target.classList.add('reveal-visible');revealObserver.unobserve(entry.target)}})},{threshold:.1,rootMargin:'0px 0px -40px 0px'});document.querySelectorAll('[data-reveal]').forEach(function(el){revealObserver.observe(el)})}else{document.querySelectorAll('[data-reveal]').forEach(function(el){el.classList.add('reveal-visible')})}
document.querySelectorAll('[data-stagger]').forEach(function(container){var children=container.children;if('IntersectionObserver' in window){var staggerObserver=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){for(var i=0;i<children.length;i++)(function(child,delay){setTimeout(function(){child.style.opacity='1';child.style.transform='translateY(0)'},delay)})(children[i],i*120);staggerObserver.unobserve(entry.target)}})},{threshold:.05,rootMargin:'0px 0px -30px 0px'});for(var i=0;i<children.length;i++){children[i].style.opacity='0';children[i].style.transform='translateY(24px)';children[i].style.transition='opacity .6s,transform .6s'}staggerObserver.observe(container)}else{for(var i=0;i<children.length;i++){children[i].style.opacity='1';children[i].style.transform='translateY(0)'}}});
var pt=document.getElementById('precioToggle');if(pt){pt.addEventListener('change',function(){isYearly=this.checked;updatePrices()})}
updatePrices();
var form=document.getElementById('contactForm');if(form){form.addEventListener('submit',function(e){e.preventDefault();var btn=form.querySelector('button[type="submit"]');var status=document.getElementById('formStatus');var orig=btn.innerHTML;btn.innerHTML='<span>Enviando...</span>';btn.disabled=true;if(status)status.style.display='none';showToast('¡Mensaje enviado! Te responderemos pronto.','#34D399');btn.innerHTML=orig;btn.disabled=false;form.reset()})}
var anchors=document.querySelectorAll('a[href^="#"]');anchors.forEach(function(a){a.addEventListener('click',function(e){var href=this.getAttribute('href');var t=document.querySelector(href);if(t){e.preventDefault();window.scrollTo({top:t.getBoundingClientRect().top+window.scrollY-80,behavior:'smooth'})}})});
document.addEventListener('keydown',function(e){if(e.key==='Escape'&&nl&&nl.classList.contains('open')){nl.classList.remove('open');nt.classList.remove('active');nt.setAttribute('aria-expanded','false');document.body.style.overflow=''}});
var heroInner=document.querySelector('.hero-inner');if(heroInner){var parallaxTimer=null;window.addEventListener('scroll',function(){if(parallaxTimer)return;parallaxTimer=setTimeout(function(){var y=window.scrollY;if(y<600){heroInner.style.transform='translateY('+(y*.3)+'px)';heroInner.style.opacity=1-(y/600)}parallaxTimer=null},16)},{passive:true})}})();